version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 172.20.0.2

  web:
    build: .
    environment:
      - FLASK_APP=app.py
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=172.20.0.2
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.3

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db_data:
